language: ruby
script: bundle exec rspec
notifications:
  email: false
  slack:
    secure: BMwvi9MTTzlQ73PQC08q1X6aIw/WLtqDOk72Q9DgzSFaF2B4u/mnFB8U0+nTNQZKSyteb8lVWMe94ISG4FZ8c+hsXVdRnhebV+jPaU8g2cu5H2x4LXa6/BRDVHqB192W5rYiGd4Oa6ETWlMf0PM0MTXJrqKgVuru4xayz4Ltv+/9Reo7G0dyNPKerMc+raBRKX/Q90Jp9N5oWZ6m0zvKruFocruUj4pK6I0+wtOy3jxNOXQTwtZLb3ttf9tL+gb2KoLaasAgXj0Se2xfNuuiDm9mnATtYAo8emChl+ZMNZRhDnfCEhdmwQrENXhkkNByRy5Lhmb0DyyopWpQClypMzV0uVn4RZQQNWqL2E3A9zsJgM/cUvK4xKpZzMVCsneNVUAT5quifgtZCz7/Yf4Cjt8GSIBr/Hl96F3iJmCA9eMuVAQyEShacZXIPsPGb4fk8g/MwmMiPxDbz9UYFJlBaKIb165iKL70SIQS7lpVicT0PhkNER/oE1Okr+z8UC9CMtC4eZpn2JULwRknmKa9VDBZaKO7y62isvDTy2pF6BtIlWQnaBNu3i0TS1y8FFLs+3l+tkD6v8sWBWhNduVrmAxnpf/qopAYAfzl+WFs9B9FiFqqLVayg9zZ3uN8EA2Hs4rIdBbCZ7aKAppj5EIxF4Vnj8DjZN9AfVhoihP5sUE=
deploy:
  provider: heroku
  api_key:
    secure: pwZ5dZb9biBnG5TANeR6K4sVob5dFl0JB7knJLcdGoNV2HInl5EC6/zpMULb9DGN8dbOrkVLKlRDKrIbTdV1Zl4da698Ixd0uz5X7lySvRf7fp4f9Ldmdbakhx6XSlOU2PeTNQR2Eptd8+GUUrHilBYfCleOWtlAC3BaLgkZR8W80Mx0V8TVSUgNISqVYRNN81AYVWxq7Xvw5gvVeosIXEHw6lmn2QY0Q48emVpqxbrw9qpjjsKmkGylpx4FhxjmedEwIkSmnd7yeNTSm5LeuRTrmC0w31aZ/fJK6JFNRNgLXbLJ3AzZUbNQQUdq+C2na8B0mVFwH8emp/Bips4yCOr2B8hGaTF4G7NUYtsTNGj7Umo1CProNuMqruovPJNJBD9PXKqq7uvn4H2SZWQv7rWUFJdMr8TvBk1Aw8TwywcwgXQ6UDLjGDfKK9rZcWgDfsxFF+7DAHGCW9JOzCH1mSkqKhwHe4AYzf96gC3+0RinSc9FGWaLmIsBhJZbXhTXmuorNPgR2TB1Sg5qeh+AZu19mRkfAPZa3dqDg5JhrDi1+UO/kRFgap8I5EuJyy7qpz2OLW87vQhcJlgGQe+aD/rVqqhN7pm5pqmpUa4BV54OC4plKYL2tBweTRTBgiriIqo2EhajYiniKc+PqsydF0iDmICC/1YpWvlmn5bmZgc=
  app: parrot-api-staging
  on:
    repo: chattermill/parrot-api
