language: ruby
script: bundle exec rspec spec
notifications:
  email: false
  slack:
    secure: BMwvi9MTTzlQ73PQC08q1X6aIw/WLtqDOk72Q9DgzSFaF2B4u/mnFB8U0+nTNQZKSyteb8lVWMe94ISG4FZ8c+hsXVdRnhebV+jPaU8g2cu5H2x4LXa6/BRDVHqB192W5rYiGd4Oa6ETWlMf0PM0MTXJrqKgVuru4xayz4Ltv+/9Reo7G0dyNPKerMc+raBRKX/Q90Jp9N5oWZ6m0zvKruFocruUj4pK6I0+wtOy3jxNOXQTwtZLb3ttf9tL+gb2KoLaasAgXj0Se2xfNuuiDm9mnATtYAo8emChl+ZMNZRhDnfCEhdmwQrENXhkkNByRy5Lhmb0DyyopWpQClypMzV0uVn4RZQQNWqL2E3A9zsJgM/cUvK4xKpZzMVCsneNVUAT5quifgtZCz7/Yf4Cjt8GSIBr/Hl96F3iJmCA9eMuVAQyEShacZXIPsPGb4fk8g/MwmMiPxDbz9UYFJlBaKIb165iKL70SIQS7lpVicT0PhkNER/oE1Okr+z8UC9CMtC4eZpn2JULwRknmKa9VDBZaKO7y62isvDTy2pF6BtIlWQnaBNu3i0TS1y8FFLs+3l+tkD6v8sWBWhNduVrmAxnpf/qopAYAfzl+WFs9B9FiFqqLVayg9zZ3uN8EA2Hs4rIdBbCZ7aKAppj5EIxF4Vnj8DjZN9AfVhoihP5sUE=
deploy:
  provider: heroku
  api_key:
    secure: QwYz3Yqw0vU8HF2a8pRpI+pVV+A7ycd4/atlNlb6lRjYqiiBWPCI0NqkojGzF0MapPLKVFbR9jtKmVhP0TW9dK3sHxY273yFBf0P0xWyLp63Y4XloR1Bto7URD0OnTgo4yYTZEjgY0Bnep0RoQMNg66tkB0m1HOO6tEjmNlfm0gd8PudsAO4mDnRlD7TIwDj6jlQ9uWypvrunjaU62kGHusoCiICshgs9mdVZfJqa8zHey7X1TeVbsr1S2gcGJP+wM9MdSAmTr6JgReqHQuSK2GZXnsC39xjJ8J4Tm+USDHtoyo5QOyw9YzNjsWMhnkUytAWZCjoMA8Lg4AuRuJUkMyHRhk+JT7Di0h2O9PEhe2SDiGWPRR4wd3DYJNSl87fX4c1VpHi6DGlDSWDS8FnaYEfQ/9p3cTTkQVVnHpflowlfCXuoRwdXZXYZYwXyjHZkYdKPT8ORRWErkAk/bH5bsJs1xF79q5quMXnwp4Ud3Gs1ymEm0GD9PTXYCLKDE+JSZ3AmGa+t/dPeFQMOXxdbK6z/zQoWYX6SZGcmeVz7N4q30YWBsTUr5B6frJA1vU6aXwEQL0+Z7TORZy9Ehlbjvikay7eoblzQkEbAY+ZEU4T5HmBzkZ3BpA8n6FLqs37ha9v/ovbadZN8R45f4EEEdGNUHgj++suAiI1WdEE8qw=
  app: parrot-api-staging
  on:
    repo: chattermill/parrot-api
