language: ruby
script: bundle exec rspec spec
notifications:
  email: false
  slack:
    secure: gG8xl9jLQE4j+xPnUhIff/lZPU8VrZIwf/ybtdV9soSRtZ19xNjfc7ldICoM3UqSRFlfopU83BhyyItu8yNGLBOftDm1VGyR2VKXxF9FQFBliJ5G2cBuP+DKg2+k42YS1amg1Oyq7U4OZ80CJq2VIJrnurDO+1kHWIZBJou4hk4=
deploy:
  provider: heroku
  api_key:
    secure: QwYz3Yqw0vU8HF2a8pRpI+pVV+A7ycd4/atlNlb6lRjYqiiBWPCI0NqkojGzF0MapPLKVFbR9jtKmVhP0TW9dK3sHxY273yFBf0P0xWyLp63Y4XloR1Bto7URD0OnTgo4yYTZEjgY0Bnep0RoQMNg66tkB0m1HOO6tEjmNlfm0gd8PudsAO4mDnRlD7TIwDj6jlQ9uWypvrunjaU62kGHusoCiICshgs9mdVZfJqa8zHey7X1TeVbsr1S2gcGJP+wM9MdSAmTr6JgReqHQuSK2GZXnsC39xjJ8J4Tm+USDHtoyo5QOyw9YzNjsWMhnkUytAWZCjoMA8Lg4AuRuJUkMyHRhk+JT7Di0h2O9PEhe2SDiGWPRR4wd3DYJNSl87fX4c1VpHi6DGlDSWDS8FnaYEfQ/9p3cTTkQVVnHpflowlfCXuoRwdXZXYZYwXyjHZkYdKPT8ORRWErkAk/bH5bsJs1xF79q5quMXnwp4Ud3Gs1ymEm0GD9PTXYCLKDE+JSZ3AmGa+t/dPeFQMOXxdbK6z/zQoWYX6SZGcmeVz7N4q30YWBsTUr5B6frJA1vU6aXwEQL0+Z7TORZy9Ehlbjvikay7eoblzQkEbAY+ZEU4T5HmBzkZ3BpA8n6FLqs37ha9v/ovbadZN8R45f4EEEdGNUHgj++suAiI1WdEE8qw=
  app: parrot-api-staging
  on:
    repo: chattermill/parrot
